### ISSUE TITLE
Categorize the rules and add small description for each of them

### ISSUE THREAD

**Issue by markelog** [jscs-dev/jscs-dev.github.io#11]
Talking about this page - http://jscs.info/rules.html

**Comment by mrjoelkemp** [comment]
Even seeing the rule's documentation in an on-hover popup would be great for fast navigation.

**Comment by mdevils** [comment]
Could you split these issues, please? They are unrelated.

**Comment by markelog** [comment]
Replaced with https://github.com/jscs-dev/jscs-dev.github.io/issues/17 https://github.com/jscs-dev/jscs-dev.github.io/issues/16
