### ISSUE TITLE
Make # links work again

### ISSUE THREAD

**Issue by markelog** [jscs-dev/jscs-dev.github.io#12]
Before, http://jscs.info/rules.html#requirelinefeedatfileend worked, now it doesn't

**Comment by mdevils** [comment]
Going to fix this soon.

**Comment by mdevils** [comment]
Partially fixes.

http://jscs.info/contributing.html#before-submitting-a-pr now works, copied header id generation algorithm from github.

**Comment by mdevils** [comment]
Fixed.
