### ISSUE TITLE
Categorize the rules

### ISSUE THREAD

**Issue by markelog** [jscs-dev/jscs-dev.github.io#16]
So it would be correctly defined under specific blocks, from https://github.com/jscs-dev/node-jscs/issues/698

Also propose to unite opposite rules - like (require | disallow)...

**Comment by mdevils** [comment]
> Also propose to unite opposite rules - like (require | disallow)...

I'm not sure about uniting. Linking from one to another is not enough? How do you think?

**Comment by markelog** [comment]
Like that -

<pre>
<h1>requireRule</h1>
Desc
Examples
etc.
...

<h1>disallowRule</h1>
Desc
Examples
etc.
...
</pre>

**Comment by hzoo** [comment]
Ref https://github.com/jscs-dev/node-jscs/pull/1752
