### ISSUE TITLE
Make configuration with gui

### ISSUE THREAD

**Issue by jt3k** [jscs-dev/jscs-dev.github.io#21]
Look what a wonderful [tool configuration in cssComb website](http://csscomb.com/config)
Let's do something like that? We need the specification in JSON.

>Посмотрите какой замечательный [инструмент конфигурации у cssComb](http://csscomb.com/config)
>Давайте сделаем нечто подобное? Нам понадобится спецификация в JSON-формате.

**Comment by hzoo** [comment]
I suggested this too https://github.com/jscs-dev/node-jscs/issues/1343#issuecomment-99430444 - however we do have the autoconfigure feature which helps you get started. Part of it is just that there's a lot of rules now.

**Comment by markelog** [comment]
Nevertheless, we will consider the PR if it would be submitted
