### ISSUE TITLE
Can't open links in new tabs

### ISSUE THREAD

**Issue by cvrebert** [jscs-dev/jscs-dev.github.io#23]
To repro:
1. Open http://jscs.info/rules.html
2. Ctrl (or Command, on Mac OS X) -click one of the rule names

Expected behavior:
The rule's page should open in a new tab, and the current tab shouldn't navigate.

Actual behavior:
No new tab opens. The current tab navigates to the rule's page.

**Comment by hzoo** [comment]
Interesting (I tried with middle click and didn't work)

**Comment by mrjoelkemp** [comment]
Seems like some custom behavior in our react app. When we remove the reactId from the `a` tag, the links open fine.

Happy to accept a PR that removes that functionality with @mdevils' blessing.

**Comment by mdevils** [comment]
Yeah, right now we're intercepting all clicks, but we actually should ignore middle-button clicks.

**Comment by jasonkarns** [comment]
@mdevils should ignore clicks with modifier keys as well, not just middle-clicks

**Comment by jasonkarns** [comment]
This issue affects the main top navigation as well, not just rule links.
