### ISSUE TITLE
Show what JSCS does on home page (picture, gif)

### ISSUE THREAD

**Issue by markelog** [jscs-dev/jscs-dev.github.io#24]
Originally reported by the @hzoo in - https://github.com/jscs-dev/node-jscs/issues/1286

--
Also I think it would be nice to give an example of what jscs does in the about/home page. config/install info - So maybe an example .jscs config that shows off the common features (preset + extend) + autofix.

**Comment by hzoo** [comment]
I think babeljs.io does a good job - we can give an example in code of an error it catches, a picture/gif of autofixing, configuring, presets.

**Comment by hzoo** [comment]
Some progress

![screen shot 2015-08-27 at 1 58 22 pm](https://cloud.githubusercontent.com/assets/588473/9528662/c0c3f7aa-4cc3-11e5-858d-982ab4642b58.png)

**Comment by markelog** [comment]
Looks pretty interesting.

Also, could you add a little hidden humor in the code/somewhere else? Like we did for the https://twitter.com/jscs_dev background image, comics like that - http://theoatmeal.com/comics/misspelling are usually inspire.

Another thing could you try to use a brighter reporter for the screen, like https://github.com/sindresorhus/grunt-eslint/blob/master/screenshot.png

**Comment by hzoo** [comment]
Yeah open to ideas! I just tried to get something going since it's needed for people new to jscs
