### ISSUE TITLE
Documentation of jscs is seriously out of date

### ISSUE THREAD

**Issue by clayreimann** [jscs-dev/jscs-dev.github.io#27]
For example [maximumLineLength](http://jscs.info/rule/maximumLineLength.html) has changed **a lot** since the last time the docs were updated.

**Comment by hzoo** [comment]
The website just needs to be updated (not sure when that happens) since the docs are tied to the files themselves. https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/maximum-line-length.js @markelog

**Comment by markelog** [comment]
> For example maximumLineLength has changed a lot since the last time the docs were updated.

Not really, for the current version this doc is up to date

> The website just needs to be updated (not sure when that happens)

When new release is out

**Comment by hzoo** [comment]
Ah ok so it updates every jscs release? Yeah maybe another reason to release maybe 3-4 weeks? ESLint tries to do 2 weeks I think.

**Comment by zxqfox** [comment]
@hzoo Definitely ;-)

**Comment by markelog** [comment]
> Ah ok so it updates every jscs release?

Not exactly, process is not fully automatic, we can fix some docs if we need to.
