### ISSUE TITLE
Wrong rendering code 

### ISSUE THREAD

**Issue by Semigradsky** [jscs-dev/jscs-dev.github.io#28]
http://jscs.info/rule/disallowNodeTypes.html

![image](https://cloud.githubusercontent.com/assets/1198848/8931911/7c1de64e-3542-11e5-80a7-9af016d86f46.png)

**Comment by hzoo** [comment]
@Semigradsky thanks for the report - it can be fixed in the rule code in the main jscs repo

**Comment by markelog** [comment]
@Semigradsky thank you for opening an issue! As @hzoo it should be fixed on the github.com/jscs-dev/node-jscs repo in here - https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-node-types.js

Should be pretty easy to fix, would you like to send us a PR?
