### ISSUE TITLE
http://jscs.info/contributing.html#prissue-closing-criteria doesn't actually have an anchor

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/jscs-dev.github.io#4]
http://jscs.info/contributing.html#prissue-closing-criteria doesn't link to a section.

**Comment by mdevils** [comment]
Thank you for report, will fix it soon!

**Comment by mikesherov** [comment]
Same goes for http://jscs.info/contributing.html#why-did-you-close-my-pull-request-or-issue , which seems to be using separate logic when generating the links vs. generating ids.
