### ISSUE TITLE
Make Presets page

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/jscs-dev.github.io#40]
What we need
- wide description of what presets is
- list of bundled presets (with examples of code?)
- a recipe to how to make a preset as NPM package (note that a plugin can store many presets at once (with a link to plugins page)

Refs
- https://github.com/jscs-dev/node-jscs/issues/1106#issuecomment-132088813

**Comment by dogancelik** [comment]
My suggestion is: A presets list (jQuery, Airbnb, Google, etc.) on Presets page, and when you click on a preset, it will automatically reformat the current example code according to the preset.

There should be at least 3 example codes, and links named `Example code #1, #2, #3` and when you click one of them and the one which clicked will change the current code in the text box.
