### ISSUE TITLE
Possible error in invalid case example on disallowPaddingNewlinesInBlocks page

### ISSUE THREAD

**Issue by am11** [jscs-dev/jscs-dev.github.io#52]
From http://jscs.info/rule/disallowPaddingNewlinesInBlocks:

<br/>

>**Valid for** `{ "open": true, "close": false, allExcept: ['conditionals'] }`
>  ```javascript
>  function (foo) {
>      return bar;
>
>  }
>
>  if (true) {
>
>      doSomething();
>
>  }
>  ```
>**Invalid**
>  ```javascript
>  if (true) {
>
>      doSomething();
>
>  }
>  ```

<br/>
<br/>

Should it instead be:

<br/>
<br/>

>**Valid for** `{ "open": true, "close": false, allExcept: ['conditionals'] }`
>  ```javascript
>  function doSomething(foo) {    // changed (jscs throws unexpected token error w/o func name)
>      return bar;
>
>  }
>
>  if (true) {
>
>      doSomething();
>
>  }
>  ```
>**Invalid**
>  ```javascript
>  function doSomething(foo) {    //changed
>      return bar;                //changed
>  }                              // changed
>  ```

**Comment by markelog** [comment]
See https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.wdv9lvm21
