### ISSUE TITLE
Typo in .jscsrc rules breaks `requireQuotedKeysInObjects`

### ISSUE THREAD

**Issue by ndarville** [jscs-dev/jscs-dev.github.io#6]
The example code for `requireQuotedKeysInObjects` reads

```json
"requiresQuotedKeysInObjects": true
```

which is bad, given that it has an `s` after `require`. This leads to an error, understandably. :)

I tried finding a place for the source code, but couldn’t spot one, so no PR.

**Comment by hzoo** [comment]
hey @ndarville, I just saw a PR for this https://github.com/jscs-dev/node-jscs/pull/1146/files (the docs actually got moved to be in the source code for the rules itself, in the node-jscs repo)

**Comment by hzoo** [comment]
Can close this.
