### ISSUE TITLE
Where is located the MD-files described in gulpfile?

### ISSUE THREAD

**Issue by jt3k** [jscs-dev/jscs-dev.github.io#7]
I plan to prepare PR and I need RULES.md file or its source files.
![imgur-2015_03_03-05 03 22](https://cloud.githubusercontent.com/assets/1261240/6455282/22fee106-c163-11e4-9d18-acd80679e51f.png)

**Comment by jt3k** [comment]
I am sorry
I found them in the 'gulp checkout'

**Comment by zxqfox** [comment]
;-) Thanks for contributing!
