### ISSUE TITLE
Link to rule source?

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/jscs-dev.github.io#8]
I think it would be cool to link to the rule source like in the ESLint docs (at the bottom) http://eslint.org/docs/rules/no-comma-dangle.html

![image](https://cloud.githubusercontent.com/assets/588473/6543136/3ec16994-c4de-11e4-9551-668ec37d413c.png)

I think it might make it less work to contribute, understand rules, or fix doc issues?

**Comment by markelog** [comment]
Good idea, of course. There is a lot could be done to improve the site overall.
