### ISSUE TITLE
Add link to overcommit?

### ISSUE THREAD

**Issue by lencioni** [jscs-dev/jscs-dev.github.io#9]
I'd like to add a link to [overcommit, a git commit hook manager](https://github.com/brigade/overcommit) that includes out-of-the-box support for JSCS to the "Friendly packages" section of this page http://jscs.info/overview.html but I'm having a hard time actually finding that content here. Am I looking in the right place?

**Comment by zxqfox** [comment]
https://github.com/jscs-dev/jscs-dev.github.io/commits/master

This repo is for autogenerated code from node-jscs repo.

You need to fix https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md file ;-)

**Comment by lencioni** [comment]
Thanks!

**Comment by zxqfox** [comment]
You are welcome ;-)
